# Configuração Cloudflare Pages + D1 + KV para aplicação profissional
# Este arquivo configura todos os serviços necessários

name = "icb-landing-page"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Configuração do banco de dados D1 (gratuito)
[[d1_databases]]
binding = "DB"
database_name = "icb_cadastros"
database_id = "your-database-id-here" # Será preenchido após criação

# Configuração do KV para rate limiting e cache (gratuito)
[[kv_namespaces]]
binding = "CADASTROS_KV"
id = "your-kv-namespace-id-here" # Será preenchido após criação
preview_id = "your-kv-preview-id-here"

# Variáveis de ambiente (secrets)
[vars]
ENVIRONMENT = "production"

# Configurações de build
[build]
command = "npm run build"
cwd = "."

# Configuração específica para Pages Functions
[pages_build_config]
# Funções ficam na pasta functions/

# Email webhook (opcional - configure se usar Zapier/Make.com)
# EMAIL_WEBHOOK_URL = "https://hooks.zapier.com/hooks/catch/..."
